Toys.Web/Models/ErrorViewModel.cs
using System;

namespace Toys.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Toys.Web/Models/PageResult.cs
using System;

using System.Collections.Generic;
using Toys.Data.Models;

namespace Toys.Web.Models
{
    public abstract class PagedResultBase
    {
        public int CurrentPage { get; set; }
        public int PageCount { get; set; }
        public int PageSize { get; set; }
        public int RowCount { get; set; }

        public int FirstRowOnPage
        {
            get { return (CurrentPage - 1) * PageSize + 1; }
        }

        public int LastRowOnPage
        {
            get { return Math.Min(CurrentPage * PageSize, RowCount); }
        }
    }

    public class PagedResult<T> : PagedResultBase where T : class
    {
        public IList<T> Results { get; set; }

        public PagedResult()
        {
            Results = new List<T>();
        }
    }
}

Toys.Web/Models/ToyPage.cs
using System;
using Toys.Data.Models;
using System.Collections.Generic;


namespace Toys.Web.Models
{
    public class ToyPage
    {
        public int CurrentPageIndex { get; set; }

        public int PageCount { get; set; }
        public List<Toy> ToyList { get; set; }
    }
}

Toys.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Toys.Web.Models;

namespace Toys.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Toys.Web/Controllers/MyCartController.cs
using System;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

using System.Collections.Generic;
using Toys.Data.Models;
using Toys.Data.Repositories;
using Toys.Web.Extensions;
using Toys.Web.Services;


namespace Toys.Web.Controllers
{
    public class MyCartController : Controller
    {
        private readonly IToyService toyService;
        private readonly IToyRepository toyRepository;

        public MyCartController(IToyRepository toyRepository, IToyService toyService)
        {
            this.toyRepository = toyRepository;
            this.toyService = toyService;
        }

        public ActionResult Index()
        {
            if (HttpContext.Session.Get("cart") == null)
            {
                List<ShoppingCart> cart = new List<ShoppingCart>();

                HttpContext.Session.SetObject("cart", cart);
            }

            return View();
        }

        private int isExist(string id)
        {
            List<ShoppingCart> cart = HttpContext.Session.GetObject<List<ShoppingCart>>("cart");
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].CToy.CToyId.Equals(id))
                    return i;
            return -1;
        }

        public ActionResult Add(string id)
        {
            if (HttpContext.Session.GetObject<List<ShoppingCart>>("cart") == null)
            {
                List<ShoppingCart> cart = new List<ShoppingCart>();
                cart.Add(new ShoppingCart { CToy = toyRepository.FindByPrimaryKey(id), SiQty = 1 });
                HttpContext.Session.SetObject("cart", cart);
            }
            else
            {
                List<ShoppingCart> cart = HttpContext.Session.GetObject<List<ShoppingCart>>("cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].SiQty++;
                }
                else
                {
                    cart.Add(new ShoppingCart { CToy = toyRepository.FindByPrimaryKey(id), SiQty = 1 });
                }
                HttpContext.Session.SetObject("cart", cart);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(string id)
        {
            List<ShoppingCart> cart = HttpContext.Session.GetObject<List<ShoppingCart>>("cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            HttpContext.Session.SetObject("cart", cart);
            return RedirectToAction("Index");
        }
    }
}

Toys.Web/Controllers/ToyController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Toys.Web.Controllers;
using Toys.Data;
using Toys.Data.Data;
using Toys.Data.Repositories;
using Toys.Web;
using Toys.Web.Services;

namespace Toys.Web.Controllers
{
    public class ToyController : Controller
    {
        private readonly IToyService toyService;

        public ToyController(IToyService toyService)
        {
            this.toyService = toyService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(toyService.GetToyPage(1));
        }

        [HttpPost]
        public IActionResult Index(int currentPageIndex)
        {
            return View(toyService.GetToyPage(currentPageIndex));
        }
    }
}

Toys.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Toys.Web/Views/MyCart/Index.cshtml
@using Microsoft.AspNetCore.Http
@using Toys.Web.Extensions
@using Toys.Data.Models

@{
    ViewBag.Title = "My Cart";

    List<ShoppingCart> myCart = Context.Session.GetObject<List<ShoppingCart>>("cart");
    var total = myCart.Sum(item => @item.CToy.MToyRate * @item.SiQty).ToString("C2");
}

<h1 style="text-align:center">My Cart</h1>

@if (myCart.Count() > 0)
{
    <table style="text-align:center" class="table table-striped">
        <thead>
            <tr>
                <td>Toy Id</td>
                <td>Toy Name</td>
                <td>Toy Description</td>
                <td>Price</td>
                <td>Quantity</td>
                <td>Total Price</td>
            </tr>
        </thead>
        <tbody>
        @foreach (ShoppingCart product in @Context.Session.GetObject<List<ShoppingCart>>("cart"))
        {
            <tr class="tableBody">
                <td>@product.CToy.CToyId</td>
                <td>@product.CToy.VToyName</td>
                <td>@product.CToy.VToyDescription</td>
                <td>@product.CToy.MToyRate.ToString("C2")</td>
                <td>@product.SiQty</td>
                <td>@(@product.CToy.MToyRate * @product.SiQty)</td>
                <td><a href="@Url.Action("Remove", "MyCart", new { Id = product.CToy.CToyId })">Delete</a></td>
            </tr>
        }

        <tr>
            <h3 style="text-align:right">Grand Total: </h3>
            <h4 style="text-align:right">@total</h4>
        </tr>
</table>
    <button style="justify-content:center">
        <a href="@Url.Action("Index", "Toy")">See Product List</a>
    </button>

}
else
{
    <h2 style="text-align:center">NO RECORDS FOUND</h2>
    <button style="justify-content:flex-end">
        <a href="@Url.Action("Index", "Toy")">See Product List</a>
    </button>
}

Toys.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Toy Universe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Toys.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Toy" asp-action="Index">Toys</a>
                        </li>



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyCart" asp-action="Index">MyCart</a>
                        </li>




                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Toys.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Toys.Web/Views/Toy/Index.cshtml
@using Toys.Data.Models
@using Toys.Data.Models

@model PagedResult<Toy>;

<h1 style="text-align:center">Toys</h1>
<hr />
<form asp-action="Index" asp-controller="Toy" method="post">
	<table style="text-align:center" class="table table-striped">
        <tr>
            <th>Toy ID</th>
            <th>Toy Name</th>
            <th>Toy Description</th>
            <th>Toy Rate</th>
            <th>Quantity</th>
        </tr>

        @foreach (var product in Model.Results)
        {
            <tr  class="tableBody" style="text-align:center">
                <td>@product.CToyId</td>
                <td>@product.VToyName</td>
                <td>@product.VToyDescription</td>
                <td>@product.MToyRate.ToString("C2")</td>
                <td>@product.SiToyQoh</td>
                <td> 
                    <a href="@Url.Action("Add", "MyCart", new { id = product.CToyId })">Add to Cart</a>
                </td>
            </tr>
        }
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            @for (int pageIndex = 1; pageIndex <= Model.PageCount; pageIndex++)
            {
                @if (pageIndex != Model.CurrentPage)
                {
                    <li class="page-item"><a class="page-link" href="javascript:pagerClick(@pageIndex);">@pageIndex</a></li>
                }
                else
                {
                    <li class="page-item active">
                        <a class="page-link" href="#">@pageIndex <span class="sr-only">(current)</span></a>
                    </li>
                }

            }
        </ul>
    </nav>
    <input type="hidden" id="currentPageIndex" name="currentPageIndex" />
</form>
<script type="text/javascript">
    function pagerClick(index) {
        document.getElementById("currentPageIndex").value = index;
        document.forms[0].submit();
    }
</script>